name: "Footprint"
description: "Generate a summary of your OSS contributions on GitHub, sorted by impact."
author: "arayofcode"

branding:
  icon: "activity"
  color: "green"

inputs:
  gh_token:
    description: "GitHub token"
    required: false
    default: ${{ github.token }}
  username:
    description: "GitHub username (defaults to GITHUB_ACTOR)"
    required: false
  output_branch:
    description: "Branch to publish generated artifacts"
    required: false
    default: "footprint-output"
  output_dir:
    description: "Output directory for artifacts"
    required: false
    default: "dist"
  min_stars:
    description: "Minimum stars for owned projects"
    required: false
    default: "5"
  card:
    description: "Generate SVG card"
    required: false
    default: "true"
  timeout:
    description: "Timeout for GitHub API operations in seconds"
    required: false
    default: "300"

outputs:
  total_contributions:
    description: "Count of discovered external contributions"
  owned_projects_count:
    description: "Count of owned OSS projects meeting the star threshold"
  total_score:
    description: "Calculated aggregate impact score"

runs:
  using: docker
  image: Dockerfile
  env:
    GITHUB_TOKEN: ${{ inputs.gh_token }}
    OUTPUT_BRANCH: ${{ inputs.output_branch }}
    OUTPUT_DIR: ${{ inputs.output_dir }}
  args:
    - "-username"
    - "${{ inputs.username }}"
    - "-output"
    - "${{ inputs.output_dir }}"
    - "-min-stars"
    - "${{ inputs.min_stars }}"
    - "-card"
    - "${{ inputs.card }}"
    - "-timeout"
    - "${{ inputs.timeout }}s"